### ISSUE TITLE
Import from HTML does not accept .html files

### ISSUE THREAD

**Issue by mangus** [skodak/moodle-mod_book#19]
When trying to importing HTML file into book element in Moodle, then error occurs:

""Test.html" is not a valid file type" -- users get confused and may think import from HTML file is not possible or the uploaded file was invalid.

The module actually needs files to be zipped into archive, but there is no information about this in user interface (i discovered it from source code :)).

Maybe it's a good idea to allow importing from single HTML file or at least put an explaining text to "Import from HTML" page.

Also -- thanks for Your work with this module! :)

**Comment by skodak** [comment]
Hello, yes the HTML import is not supported because you can not easily upload multiple files, it is very different from 1.9 where you were just pointing to course files, in 2.0 the zip archive seems to be the only reasonable way to upload multiple files. If you have just html files without images and other media you can copy&paste it directly into editor. I am going to fix the element name and inline help, thanks.

**Comment by skodak** [comment]
Fix committed, thanks for the report.

**Comment by mangus** [comment]
Thanks for very fast reaction! :)
